apiVersion: v1
kind: Namespace
metadata:
  name: jboss-deployment
  labels:
    apps: web-based
  annotations:
---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: mem-cpu-quota
  namespace: jboss-deployment
spec:
  hard:
    requests.cpu: "4"
    requests.memory: 8Gi
    limits.cpu: "8"
    limits.memory: 16Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: bookstore
  labels:
    app: jboss
  namespace: jboss-deployment
  annotations:
    monitoring: "true"
spec:
  replicas: 3
  selector:
    matchLabels:
      app: jboss
  template:
    metadata:
      labels:
        app: jboss
    spec:
      containers:
      - image: steju480/jboss:latest
        name: bookstore
        ports:
        - containerPort: 8080
        resources:
          limits:
            memory: "2Gi"
            cpu: "1000m"
          requests:
            memory: "1Gi"
            cpu: "500m"
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: jboss
  name: jboss-service
  namespace: jboss-deployment
spec:
  ports:
  - nodePort: 30001
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: jboss
  type: NodePort
